apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: changeme
spec:
  rules:
  - host: changeme.com
    http:
      paths:
      - path: /changeme
        backend:
          serviceName: changeme-svc
          servicePort: 80