apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replaceme
spec:
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      ssd: true
---
