apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: replaceme
  labels:
    app: replaceme
spec:
  replicas: 1
  
  # Pod Template
  template:
    metadata:
      labels:
        app: replaceme
    spec:
      volumes:
       - name: data
         persistentVolumeClaim:
           claimName: data
           
      containers:
       - image: changeme
         name: changeme
         ports:
         - containerPort: 8080
           name: http
           protocol: TCP
         volumeMounts:
          - name: data
            mountPath: /data
---
